name: NodeJS with Webpack

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Create Tag
        id: create_tag
        run: |
          # Calculate the version based on your project's versioning logic
          version=$(npm --no-git-tag-version version)
          git tag $version
          echo "::set-output name=tag::$version"          

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
          tag_name: ${{ steps.create_tag.outputs.tag }}
